### ISSUE TITLE
完整的代码

### ISSUE THREAD

**Issue by DylanMaeng** [best-xiaoqiang/note-sm#1]
你好，本人小白 最近也在做一个微信小程序，需要背景音乐控制，看了你的代码，很受启发，但是自己实现起来老出错，请问你可以分享一下代码片段吗，具体怎么在页面调用的，非常感谢。

**Comment by best-xiaoqiang** [comment]
页面wxml中对组件加上id:
```
<music id="music-component" />
```

页面js中调用的：
```
// 写在调用页面中:
onShow: function () {
    this.selectComponent('#music-component').onShow()
},

onHide: function () {
    this.selectComponent('#music-component').onHide()
}
```

页面json中不要忘记将组件引入。

**Comment by SagerMaeng** [comment]
> 页面wxml中对组件加上id:
> 
> ```
> <music id="music-component" />
> ```
> 
> 页面js中调用的：
> 
> ```
> // 写在调用页面中:
> onShow: function () {
>     this.selectComponent('#music-component').onShow()
> },
> 
> onHide: function () {
>     this.selectComponent('#music-component').onHide()
> }
> ```
> 
> 页面json中不要忘记将组件引入。

我这里出现了一个错误呀
![image](https://user-images.githubusercontent.com/33370349/57452707-0faaf100-7297-11e9-987f-aea5a337e99a.png)
这是引用
![image](https://user-images.githubusercontent.com/33370349/57452734-23565780-7297-11e9-8c91-c76e4e6bd891.png)

**Comment by best-xiaoqiang** [comment]
https://github.com/best-xiaoqiang/note-sm/issues/1#issuecomment-490878524

应该是文章中的一处错误拼写把你带跑偏了。把wxml里的music-componet改成music-component试试。这里有些微的拼写错误。。。（希望这样回复能通知到你）

**Comment by best-xiaoqiang** [comment]
https://github.com/best-xiaoqiang/note-sm/issues/1#issuecomment-490878524

应该是文章中的一处错误拼写把你带跑偏了。把wxml里的music-componet改成music-component试试。这里有些微的拼写错误。。。（希望这样回复能通知到你）

**Comment by DylanMaeng** [comment]
> [#1 (comment)](https://github.com/best-xiaoqiang/note-sm/issues/1#issuecomment-490878524)
> 
> 应该是文章中的一处错误拼写把你带跑偏了。把wxml里的music-componet改成music-component试试。这里有些微的拼写错误。。。（希望这样回复能通知到你）

我也发现了 是我太疏忽

**Comment by DylanMaeng** [comment]
> 页面wxml中对组件加上id:
> 
> ```
> <music id="music-component" />
> ```
> 
> 页面js中调用的：
> 
> ```
> // 写在调用页面中:
> onShow: function () {
>     this.selectComponent('#music-component').onShow()
> },
> 
> onHide: function () {
>     this.selectComponent('#music-component').onHide()
> }
> ```
> 
> 页面json中不要忘记将组件引入。

还想请教一下你 如果多个页面共同调用这个组件 音乐能连上来吗
